version: '3'

services:
  db:
    image: postgres
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: estoque
    ports:
      - 5432
    expose:
      - 5432:5432

  # SGBD Dockerizado
  adminerdb:
    image: adminer
    restart: always
    ports: 
      - 8080:8080